/**
 * CSE Company Dataset — @LochanaKa
 * Data Science • Economics • Markets
 *
 * HOW TO EDIT:
 * - status:       "listed" | "merged" | "delisted"
 * - sector:       Must match a value in SECTORS array exactly
 * - listedYear:   Replace null with verified year e.g. 1994
 * - analysisUrl:  Replace "#" with your research page URL
 * - mergedInto:   (merged only) Name of absorbing company
 * - delistedNote: (delisted only) Brief reason for delisting
 *
 * To add a company: copy a row, edit values. No other file needs changing.
 */

const SECTORS = [
  "Banking & Finance",
  "Insurance",
  "Diversified Holdings",
  "Telecommunications",
  "Food, Beverage & Tobacco",
  "Hotels & Travel",
  "Plantations",
  "Manufacturing",
  "Construction & Materials",
  "Healthcare",
  "Consumer Goods & Retail",
  "Energy & Power",
  "Real Estate & Property",
  "Motors & Transportation",
  "Information Technology",
  "Investment Trusts",
  "Other"
];

const COMPANIES = [

  // ============================================================
  //  CURRENTLY LISTED  (289 companies)
  // ============================================================
  { ticker: "ABAN.N0000", name: "Abans Electricals PLC", sector: "Consumer Goods & Retail", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "AFSL.N0000", name: "Abans Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "AEL.N0000", name: "Access Engineering PLC", sector: "Construction & Materials", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ACL.N0000", name: "ACL Cables PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "APLA.N0000", name: "ACL Plastics PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ACME.N0000", name: "ACME Printing & Packaging PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "AGAL.N0000", name: "Agalawatte Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "AGPL.N0000", name: "Agarapatana Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "AGST.N0000", name: "AgStar PLC", sector: "Other", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "AHUN.N0000", name: "Aitken Spence Hotel Holdings PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SPEN.N0000", name: "Aitken Spence PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ALLI.N0000", name: "Alliance Finance Company PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "AFS.N0000", name: "Alpha Fire Services PLC", sector: "Other", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ALUM.N0000", name: "Alumex PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ABL.N0000", name: "Amana Bank PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ATL.R0000", name: "Amana Takaful PLC", sector: "Insurance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ATLL.N0000", name: "Amana Takaful Life PLC", sector: "Insurance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "TAP.N0000", name: "Ambeon Capital PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "GREG.N0000", name: "Ambeon Holdings PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "AMCL.N0000", name: "AMW Capital Leasing and Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ALHP.N0000", name: "Anilana Hotels and Properties PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "AINS.N0000", name: "Arpico Insurance PLC", sector: "Insurance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "AAF.N0000", name: "Asia Asset Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ACAP.N0000", name: "Asia Capital PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ASIY.N0000", name: "Asia Siyaka Commodities Limited", sector: "Other", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "AHPL.N0000", name: "Asian Hotels and Properties PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ASIR.N0000", name: "Asiri Hospital Holdings PLC", sector: "Healthcare", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "AMSL.N0000", name: "Asiri Surgical Hospital PLC", sector: "Healthcare", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "AMF.N0000", name: "Associated Motor Finance Company PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "BPPL.N0000", name: "BPPL Holdings PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "BFL.N0000", name: "Bairaha Farms PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "BALA.N0000", name: "Balangoda Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "BRR.N0000", name: "Bansei Royal Resorts Hikkaduwa PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "BERU.N0000", name: "Beruwala Resorts PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "BLUE.N0000", name: "Blue Diamonds Jewellery Worldwide PLC", sector: "Consumer Goods & Retail", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "BOGA.N0000", name: "Bogala Graphite Lanka PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "BOPL.N0000", name: "Bogawantalawa Tea Estates PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "BRWN.N0000", name: "Brown & Company PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "BBH.N0000", name: "Browns Beach Hotels PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "BIL.N0000", name: "Browns Investments PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "BUKI.N0000", name: "Bukit Darah PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CIC.N0000", name: "CIC Holdings PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "COLO.N0000", name: "C M Holdings PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CTHR.N0000", name: "C T Holdings PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CTLD.N0000", name: "CT Land Development PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CWM.N0000", name: "C. W. Mackie PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CSLK.N0000", name: "Cable Solutions PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CALC.U0000", name: "CAL Five Year Closed End Fund", sector: "Investment Trusts", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CALI.U0000", name: "CAL Five Year Optimum Fund", sector: "Investment Trusts", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CALU.U0000", name: "CAL Three Year Closed End Fund", sector: "Investment Trusts", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CALH.N0000", name: "Capital Alliance Holdings PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CALT.N0000", name: "Capital Alliance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CARG.N0000", name: "Cargills (Ceylon) PLC", sector: "Consumer Goods & Retail", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CBNK.N0000", name: "Cargills Bank PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CABO.N0000", name: "Cargo Boat Development Company PLC", sector: "Motors & Transportation", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CARS.N0000", name: "Carson Cumberbatch PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CFIN.N0000", name: "Central Finance Company PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CIND.N0000", name: "Central Industries PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CINS.N0000", name: "Ceylinco Holdings PLC", sector: "Insurance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "BREW.N0000", name: "Ceylon Beverage Holdings PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CCS.N0000", name: "Ceylon Cold Stores PLC", sector: "Consumer Goods & Retail", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "GRAN.N0000", name: "Ceylon Grain Elevators PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "GUAR.N0000", name: "Ceylon Guardian Investment Trust PLC", sector: "Investment Trusts", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CHL.N0000", name: "Ceylon Hospitals PLC", sector: "Healthcare", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CHOT.N0000", name: "Ceylon Hotels Corporation PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CINV.N0000", name: "Ceylon Investment PLC", sector: "Investment Trusts", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "KZOO.N0000", name: "Ceylon Land & Equity PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CLPL.N0000", name: "Ceylon Leather Products PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CTBL.N0000", name: "Ceylon Tea Brokers PLC", sector: "Other", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CTC.N0000", name: "Ceylon Tobacco Company PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CHMX.N0000", name: "Chemanex PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LLUB.N0000", name: "Chevron Lubricants Lanka PLC", sector: "Energy & Power", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CWL.N0000", name: "Chrisworld PLC", sector: "Other", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CDB.N0000", name: "Citizens Development Business Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "REEF.N0000", name: "Citrus Leisure PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CHOU.N0000", name: "City Housing & Real Estate Co. PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "PHAR.N0000", name: "Colombo City Holdings PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "DOCK.N0000", name: "Colombo Dockyard PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CFI.N0000", name: "Colombo Fort Investments PLC", sector: "Investment Trusts", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CIT.N0000", name: "Colombo Investment Trust PLC", sector: "Investment Trusts", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CLND.N0000", name: "Colombo Land and Development Company PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "COMB.N0000", name: "Commercial Bank of Ceylon PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "COCR.N0000", name: "Commercial Credit and Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "COMD.N0000", name: "Commercial Development Company PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SOY.N0000", name: "Convenience Foods Lanka PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "COOP.N0000", name: "Co-operative Insurance Company PLC", sector: "Insurance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "DPL.N0000", name: "Dankotuwa Porcelain PLC", sector: "Construction & Materials", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "DFCC.N0000", name: "DFCC Bank PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "DIAL.N0000", name: "Dialog Axiata PLC", sector: "Telecommunications", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CALF.N0000", name: "Dialog Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "DIMO.N0000", name: "Diesel & Motor Engineering PLC", sector: "Motors & Transportation", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "PKME.N0000", name: "Digital Mobility Solutions Lanka PLC", sector: "Information Technology", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CTEA.N0000", name: "Dilmah Ceylon Tea Company PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "DIPD.N0000", name: "Dipped Products PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "DIST.N0000", name: "Distilleries Company of Sri Lanka PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "STAF.N0000", name: "Dolphin Hotels PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ECL.N0000", name: "E-Channelling PLC", sector: "Information Technology", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "EBCR.N0000", name: "EB Creasy & Company PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "EML.N0000", name: "EML Consultants PLC", sector: "Other", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "EAST.N0000", name: "East West Properties PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "EMER.N0000", name: "Eastern Merchants PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "EDEN.N0000", name: "Eden Hotel Lanka PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ELPL.N0000", name: "Elpitiya Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ETWO.N0000", name: "Equity Two PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "PACK.N0000", name: "Ex-pack Corrugated Cartons PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "EXT.N0000", name: "Exterminators PLC", sector: "Other", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CFVF.N0000", name: "First Capital Holdings PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "FCT.N0000", name: "First Capital Treasuries PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "GHLL.N0000", name: "Galadari Hotels (Lanka) PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "WAPO.N0000", name: "Galle Face Capital Partners PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "GEST.N0000", name: "Gestetner of Ceylon PLC", sector: "Other", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MEL.N0000", name: "Greentech Energy PLC", sector: "Energy & Power", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HAPU.N0000", name: "Hapugastenne Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HARI.N0000", name: "Harischandra Mills PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HNB.N0000", name: "Hatton National Bank PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HPL.N0000", name: "Hatton Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HAYC.N0000", name: "Haycarb PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MGT.N0000", name: "Hayleys Fabric PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HEXP.N0000", name: "Hayleys Fibre PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CONN.N0000", name: "Hayleys Leisure PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HAYL.N0000", name: "Hayleys PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HDFC.N0000", name: "HDFC Bank of Ceylon PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "Analyse-Doc-Page/analysis.html?ticker=HDFC.N0000", status: "listed" },
  { ticker: "HELA.N0000", name: "Hela Apparel Holdings PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HHL.N0000", name: "Hemas Holdings PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CITH.N0000", name: "Hikkaduwa Beach Resort PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HNBF.N0000", name: "HNB Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HASU.N0000", name: "HNB Life PLC", sector: "Insurance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HOPL.N0000", name: "Horana Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HSIG.N0000", name: "Hotel Sigiriya PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HBS.N0000", name: "hSenid Business Solutions PLC", sector: "Information Technology", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HUNA.N0000", name: "Hunas Holdings PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HUNT.N0000", name: "Hunter & Company PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HVA.N0000", name: "HVA Foods PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "INDO.N0000", name: "Indo Malay PLC", sector: "Other", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ASPH.N0000", name: "Industrial Asphalts (Ceylon) PLC", sector: "Construction & Materials", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "INME.N0000", name: "Insureme Insurance Brokers PLC", sector: "Insurance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "BFN.N0000", name: "Janashakthi Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "JINS.N0000", name: "Janashakthi Insurance PLC", sector: "Insurance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "JXG.N0000", name: "Janashakthi Limited", sector: "Insurance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "JAT.N0000", name: "JAT Holdings PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "JETS.N0000", name: "Jetwing Symphony PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "JFP.N0000", name: "JF Packaging PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "JKH.N0000", name: "John Keells Holdings PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "Analyse-Doc-Page/analysis.html?ticker=JKH.N0000", status: "listed" },
  { ticker: "KHL.N0000", name: "John Keells Hotels PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "JKL.N0000", name: "John Keells PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "KAHA.N0000", name: "Kahawatte Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "KPHL.N0000", name: "Kapruka Holdings PLC", sector: "Consumer Goods & Retail", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "KFP.N0000", name: "Keells Food Products PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "KGAL.N0000", name: "Kegalle Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "KCAB.N0000", name: "Kelani Cables PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "TYRE.N0000", name: "Kelani Tyres PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "KVAL.N0000", name: "Kelani Valley Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "KDL.N0000", name: "Kelsey Developments PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CPRT.N0000", name: "Kerner Haus Global Solutions PLC", sector: "Other", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "KOTA.N0000", name: "Kotagala Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LAMB.N0000", name: "Kotmale Holdings PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LOLC.N0000", name: "LOLC Holdings PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LVEF.N0000", name: "LVL Energy Fund PLC", sector: "Energy & Power", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LPRT.N0000", name: "Lake House Printers & Publishers PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LALU.N0000", name: "Lanka Aluminium Industries PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ASHO.N0000", name: "Lanka Ashok Leyland PLC", sector: "Motors & Transportation", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CERA.N0000", name: "Lanka Ceramic PLC", sector: "Construction & Materials", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LCBF.N0000", name: "Lanka Credit and Business Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LIOC.N0000", name: "Lanka IOC PLC", sector: "Energy & Power", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LMF.N0000", name: "Lanka Milk Foods (CWE) PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ASCO.N0000", name: "Lanka Realty Investments PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "TILE.N0000", name: "Lanka Tiles PLC", sector: "Construction & Materials", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LVEN.N0000", name: "Lanka Ventures PLC", sector: "Energy & Power", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LWL.N0000", name: "Lanka Walltile PLC", sector: "Construction & Materials", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LCEY.N0000", name: "Lankem Ceylon PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LDEV.N0000", name: "Lankem Developments PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LGL.N0000", name: "LAUGFS Gas PLC", sector: "Energy & Power", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LPL.N0000", name: "LAUGFS Power PLC", sector: "Energy & Power", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LITE.N0000", name: "Laxapana PLC", sector: "Energy & Power", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LFIN.N0000", name: "LB Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SHAW.N0000", name: "Lee Hedges PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LION.N0000", name: "Lion Brewery (Ceylon) PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LOFC.N0000", name: "LOLC Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LGIL.N0000", name: "LOLC General Insurance PLC", sector: "Insurance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HPFL.N0000", name: "Lotus Hydro Power PLC", sector: "Energy & Power", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LUMX.N0000", name: "Luminex PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MADU.N0000", name: "Madulsima Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MFPE.N0000", name: "Maharaja Foods PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MCPL.N0000", name: "Mahaweli Coconut Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MRH.N0000", name: "Mahaweli Reach Hotels PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MAL.N0000", name: "Malwatte Valley Plantation PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MARA.N0000", name: "Marawila Resorts PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MASK.N0000", name: "Maskeliya Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MELS.N0000", name: "Melstacorp PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MERC.N0000", name: "Mercantile Investments and Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MSL.N0000", name: "Mercantile Shipping Company PLC", sector: "Motors & Transportation", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MBSL.N0000", name: "Merchant Bank of Sri Lanka & Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MHDL.N0000", name: "Millennium Housing Developers PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MIRA.N0000", name: "Miramar Beach Hotel PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MULL.N0000", name: "Muller & Phipps (Ceylon) PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "MDL.N0000", name: "Myland Developments PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "NAVF.U0000", name: "Namal Acuity Value Fund", sector: "Investment Trusts", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "NAMU.N0000", name: "Namunukula Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CSF.N0000", name: "Nation Lanka Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "NDB.N0000", name: "National Development Bank PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "NTB.N0000", name: "Nations Trust Bank PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "NHL.N0000", name: "Nawaloka Hospitals PLC", sector: "Healthcare", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ODEL.N0000", name: "Odel PLC", sector: "Consumer Goods & Retail", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "OFEQ.N0000", name: "Office Equipment PLC", sector: "Other", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "ONAL.N0000", name: "On'ally Holdings PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "OSEA.N0000", name: "Overseas Realty (Ceylon) PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "Analyse-Doc-Page/analysis.html?ticker=OSEA.N0000", status: "listed" },
  { ticker: "PALM.N0000", name: "Palm Garden Hotels PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "PABC.N0000", name: "Pan Asia Banking Corporation PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "PAP.N0000", name: "Panasian Power PLC", sector: "Energy & Power", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "PARA.N0000", name: "Paragon Ceylon PLC", sector: "Other", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "PCPH.N0000", name: "PC Pharma PLC", sector: "Healthcare", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "PEG.N0000", name: "Pegasus Hotels of Ceylon PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "PINS.N0000", name: "People's Insurance PLC", sector: "Insurance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "PLC.N0000", name: "People's Leasing & Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "GLAS.N0000", name: "PGP Glass Ceylon PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "PMB.N0000", name: "PMF Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "PLR.N0000", name: "Prime Lands Residencies PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CARE.N0000", name: "Printcare PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "RIL.N0000", name: "R I L Property PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "RGEM.N0000", name: "Radiant Gems International PLC", sector: "Consumer Goods & Retail", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "RWSL.N0000", name: "Raigam Wayamba Salterns PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "RFL.N0000", name: "Ramboda Falls PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "RAL.N0000", name: "Renuka Agri Foods PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "RENU.N0000", name: "Renuka City Hotels PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "COCO.N0000", name: "Renuka Foods PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "RHL.N0000", name: "Renuka Holdings PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "RCH.N0000", name: "Renuka Hotels PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "HPWR.N0000", name: "Resus Energy PLC", sector: "Energy & Power", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "RICH.N0000", name: "Richard Pieris and Company PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "REXP.N0000", name: "Richard Pieris Exports PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "RCL.N0000", name: "Royal Ceramics Lanka PLC", sector: "Construction & Materials", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "RPBH.N0000", name: "Royal Palms Beach Hotels PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SAMP.N0000", name: "Sampath Bank PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SIL.N0000", name: "Samson International PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SDB.N0000", name: "SANASA Development Bank PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SDF.N0000", name: "Sarvodaya Development Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SMOT.N0000", name: "Sathosa Motors PLC", sector: "Motors & Transportation", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SFCL.N0000", name: "Senkadagala Finance Company PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SHOT.N0000", name: "Serendib Hotels PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SLND.N0000", name: "Serendib Land PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SEYB.N0000", name: "Seylan Bank PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CSD.N0000", name: "Seylan Developments PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SIRA.N0000", name: "Sierra Cables PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SIGV.N0000", name: "Sigiriya Village Hotels PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SINS.N0000", name: "Singer (Sri Lanka) PLC", sector: "Consumer Goods & Retail", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SFIN.N0000", name: "Singer Finance Lanka PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SINH.N0000", name: "Singhe Hospitals PLC", sector: "Healthcare", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SEMB.N0000", name: "SMB Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SCAP.N0000", name: "Softlogic Capital PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CRL.N0000", name: "Softlogic Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SHL.N0000", name: "Softlogic Holdings PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "AAIC.N0000", name: "Softlogic Life Insurance PLC", sector: "Insurance", listedYear: null, analysisUrl: "Analyse-Doc-Page/analysis.html?ticker=AAIC.N0000", status: "listed" },
  { ticker: "SLTL.N0000", name: "Sri Lanka Telecom PLC", sector: "Telecommunications", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SING.N0000", name: "Standard Capital PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SUN.N0000", name: "Sunshine Holdings PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SWAD.N0000", name: "Swadeshi Industrial Works PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "PARQ.N0000", name: "Swisstek (Ceylon) PLC", sector: "Construction & Materials", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "TAJ.N0000", name: "TAL Lanka Hotels PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "TPL.N0000", name: "Talawakelle Tea Estates PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "TANG.N0000", name: "Tangerine Beach Hotels PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "TSML.N0000", name: "Tea Smallholder Factories PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "TJL.N0000", name: "Teejay Lanka PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "TESS.N0000", name: "Tess Agro PLC", sector: "Other", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LHL.N0000", name: "The Lighthouse Hotel PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "AUTO.N0000", name: "The Autodrome PLC", sector: "Motors & Transportation", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CFLB.N0000", name: "The Colombo Fort Land and Building PLC", sector: "Real Estate & Property", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "RHTL.N0000", name: "The Fortress Resorts PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "KHC.N0000", name: "The Kandy Hotels Company (1938) PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "SERV.N0000", name: "The Kingsbury PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "LHCL.N0000", name: "The Lanka Hospitals Corporation PLC", sector: "Healthcare", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "NEH.N0000", name: "The Nuwara Eliya Hotels Company PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "TAFL.N0000", name: "Three Acre Farms PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "TKYO.N0000", name: "Tokyo Cement Company (Lanka) PLC", sector: "Construction & Materials", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "TRAN.N0000", name: "Trans Asia Hotels PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "UBF.N0000", name: "UB Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "UDPL.N0000", name: "Udapussellawa Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "UAL.N0000", name: "Union Assurance PLC", sector: "Insurance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "UBC.N0000", name: "Union Bank of Colombo PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "UCAR.N0000", name: "Union Chemicals Lanka PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "UML.N0000", name: "United Motors Lanka PLC", sector: "Motors & Transportation", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "VFIN.N0000", name: "Vallibel Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "VONE.N0000", name: "Vallibel One PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "VPEL.N0000", name: "Vallibel Power Erathna PLC", sector: "Energy & Power", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "VLL.N0000", name: "Vidullanka PLC", sector: "Energy & Power", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "CITW.N0000", name: "Waskaduwa Beach Resort PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "WATA.N0000", name: "Watawala Plantations PLC", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "WLTH.N0000", name: "WealthTrust Securities PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "WIND.N0000", name: "WindForce PLC", sector: "Energy & Power", listedYear: null, analysisUrl: "#", status: "listed" },
  { ticker: "YORK.N0000", name: "York Arcade Holdings PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "listed" },

  // ============================================================
  //  MERGED COMPANIES  (7 companies)
  //  No longer trade independently — absorbed into another entity
  // ============================================================
  { ticker: "DVBD.N0000", name: "DFCC Vardhana Bank PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "merged", mergedInto: "DFCC Bank PLC", mergedNote: "Amalgamated with DFCC Bank in October 2015" },
  { ticker: "CSEC.N0000", name: "Dunamis Capital PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "merged", mergedInto: "Janashakthi PLC", mergedNote: "Amalgamated December 2019 with Janashakthi PLC" },
  { ticker: "NIFL.N0000", name: "LOLC Development Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "merged", mergedInto: "LOLC Finance PLC", mergedNote: "Amalgamated with LOLC Finance PLC in 2022 and delisted from CSE" },
  { ticker: "SMLL.N0000", name: "People's Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "merged", mergedInto: "People's Leasing & Finance PLC", mergedNote: "Merged with People's Leasing & Finance PLC in 2013/14" },
  { ticker: "REG.N0000", name: "Regnis (Lanka) PLC", sector: "Consumer Goods & Retail", listedYear: null, analysisUrl: "#", status: "merged", mergedInto: "Singer (Sri Lanka) PLC", mergedNote: "Merged with Singer (Sri Lanka) PLC on January 31, 2024" },
  { ticker: "BHR.N0000", name: "Riverina Hotels PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "merged", mergedInto: "Palm Garden Hotels PLC", mergedNote: "Amalgamated with Palm Garden Hotels PLC in 2012" },
  { ticker: "TFIL.N0000", name: "Trade Finance & Investments PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "merged", mergedInto: "Commercial Credit and Finance PLC", mergedNote: "Amalgamated into Commercial Credit and Finance PLC in December 2020" },

  // ============================================================
  //  DELISTED COMPANIES  (26 companies)
  //  Removed from CSE listing
  // ============================================================
  { ticker: "PCHH.N0000", name: "Adam Capital PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Trading suspended since 2018 for non-compliance; later delisted" },
  { ticker: "AINV.N0000", name: "Adam Investment PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Applied for delisting in 2021" },
  { ticker: "CTCE.N0000", name: "AIA Insurance Lanka PLC", sector: "Insurance", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Delisting process began July 2018; parent AIA Group listed on Hong Kong Stock Exchange" },
  { ticker: "ASPM.N0000", name: "Aitken Spence Plantation Managements Ltd", sector: "Plantations", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Proposed for delisting as of May 28, 2024" },
  { ticker: "ALUF.N0000", name: "Alufab PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Delisted from CSE in April 2024" },
  { ticker: "ARPI.N0000", name: "Arphico Finance Company PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Not actively trading but listed" },
  { ticker: "ASHA.N0000", name: "Asiri Central Hospitals PLC", sector: "Healthcare", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Delisted from CSE; changed name to Asiri Centrals Hospital Limited" },
  { ticker: "BINN.N0000", name: "Beruwela Walk Inn PLC", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "84% of shareholders approved delisting in April 2014" },
  { ticker: "BLI.N0000", name: "Bimputh Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "License cancelled by Central Bank September 2023; in liquidation since February 2025" },
  { ticker: "CIFL.N0000", name: "Central Investments & Finance Limited", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Liquidated; license cancelled by Central Bank in 2018 due to mismanagement & fraud" },
  { ticker: "CFT.N0000", name: "Ceylon & Foreign Trades PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Delisted from CSE in 2021" },
  { ticker: "CFL.N0000", name: "Chilaw Finance Ltd", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "License cancelled by Central Bank in June 2017" },
  { ticker: "EXPO.N0000", name: "Expolanka Holdings PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Shares delisted from CSE on September 12, 2024" },
  { ticker: "HUEJ.N0000", name: "Huejay International Investments PLC", sector: "Investment Trusts", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Delisted from CSE on September 6, 2020" },
  { ticker: "CITK.N0000", name: "Kalpitiya Beach Resort Limited", sector: "Hotels & Travel", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Delisted from CSE; no longer exists as a separate entity" },
  { ticker: "KURU.N0000", name: "Kuruwita Textile Mills PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Delisted from CSE; no longer exists as a separate listed entity" },
  { ticker: "LCEM.N0000", name: "Lanka Cement PLC", sector: "Construction & Materials", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Not actively listed; factory ceased production in 1991; now subsidiary of Sri Lanka Cement Corporation" },
  { ticker: "MPRH.N0000", name: "Metropolitan Resource Holdings PLC", sector: "Other", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Delisted from CSE since 2016" },
  { ticker: "KAPI.N0000", name: "MTD Walkers PLC", sector: "Construction & Materials", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Delisted from CSE on December 1, 2022 after financial difficulties" },
  { ticker: "MFL.N0000", name: "Multi Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Merged with LB Finance PLC in August 2024" },
  { ticker: "NEST.N0000", name: "Nestle Lanka PLC", sector: "Food, Beverage & Tobacco", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Delisted from CSE on August 9, 2023; became private company" },
  { ticker: "OGL.N0000", name: "Orient Garments PLC", sector: "Manufacturing", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Compulsorily wound up by Commercial High Court in October 2016" },
  { ticker: "SHAL.N0000", name: "Shalimar (Malay) PLC", sector: "Diversified Holdings", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Delisted from CSE in January 2024; now subsidiary of Goodhope Asia Holdings Ltd" },
  { ticker: "SFL.N0000", name: "Sinhaputhra Finance PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Delisted after 2019 regulatory issues" },
  { ticker: "SFS.N0000", name: "Swarnamahal Financial Services PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Finance licence cancelled by Central Bank on December 28, 2022; now defunct" },
  { ticker: "TFC.N0000", name: "The Finance Company PLC", sector: "Banking & Finance", listedYear: null, analysisUrl: "#", status: "delisted", delistedNote: "Finance licence cancelled by Central Bank effective May 22, 2020; now defunct" },

];

// Export for Node.js / build tools
if (typeof module !== "undefined" && module.exports) {
  module.exports = { COMPANIES, SECTORS };
}
